### PR TITLE
improving a bit chapter2

### PR DESCRIPTION
**Pull request by defuneste**
Small improvement on chapter2:

-  correcting typos 
- trying to make marginal distribution and probability a bit more clear 
- added the formula of joint probability linked to conditional probability times marginal probability summing up this part of the chapter

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
Thanks! I love that you did this, and need to encourage people to do it as a way to review!

**Comment by defuneste** [comment]
Hi Jon, I think it failed because of the `images/` change.  Let me see if I can correct that quickly! ++

**Comment by jonthegeek** [comment]
> Hi Jon, I think it failed because of the `images/` change. Let me see if I can correct that quickly! ++

@defuneste Doh, yes! I meant to fix this right away and then got distracted by something else! I can fix fast if you're not sure.

**Comment by defuneste** [comment]
No worries I do it quickly!

**Review by jonthegeek — APPROVED** [review]
Thanks!

**Pull request merged**
