### PR TITLE
Chapter 19 notes added

### PR DESCRIPTION
**Pull request by DrEntropy**
Adds notes for chapter 19, also minor change to chapter 18 (remove font specification to  make it more portable).

### CODE REVIEW

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Eek, that climb_model_2.Rds is 38.5MB. Can you do without it? Having something that big in the repo makes things really ugly as we make changes (github vs large files = badness).

**Review by jonthegeek — DISMISSED** [review]
Woot, this should be great as long as it builds!

**Review by jonthegeek — APPROVED** [review]
Sweet, thanks!

**Comment by DrEntropy** [comment]
Ok i rebased to remove the large dataset file and then removed dependancy on the large dataset!

**Pull request merged**
